---
# tasks file for git
- name: install...
  package: name={{item}} state=present
  with_items:
    - git

- name: install system gitconfig
  template: >-
    src=etc/gitconfig.j2
    dest=/etc/gitconfig
    owner=root
    group=root
    mode=0644
    
